ALTER SESSION SET NLS_DATE_FORMAT = "DD/MM/YYYY";

SELECT CD_FUNC,
NM_FUNCIONARIO,
DT_NASCIMENTO "DATA DE NASCIMENTO",
DS_ESTADO_CIVIL,
VL_SALARIO, 
DT_ADMISSAO "DATA INICIO TRABALHO" 
FROM T_SIP_FUNCIONARIO 
ORDER BY DT_ADMISSAO;

SELECT CD_PROJETO,
NM_PROJETO,
VL_BUDGET_PROJETO,
DT_INICIO "DATA_INICIO",
DT_TERMINO "DATA_TERMINO"
FROM T_SIP_PROJETO
ORDER BY DT_INICIO DESC;

SELECT CD_PROJETO,
NM_PROJETO,
VL_BUDGET_PROJETO,
DT_INICIO "DATA_INICIO",
DT_TERMINO "DATA_TERMINO"
FROM T_SIP_PROJETO
WHERE DT_TERMINO IS NOT NULL;

SELECT CD_FUNC "MATRICULA",
NM_FUNCIONARIO "NOME_FUNCIONARIO",
VL_SALARIO "Salário Bruto",
CD_DEPTO "CODIGO_DEPARTAMENTO",
DS_ESTADO_CIVIL "ESTADO CIVIL",
DT_NASCIMENTO "DATA DE NASCIMENTO",
DT_ADMISSAO "DATA DE CONTRATAÇÂO"
FROM T_SIP_FUNCIONARIO
WHERE CD_DEPTO IN (7,10,60);

SELECT CD_FUNC,
NM_FUNCIONARIO AS "nome do funcionario",
VL_SALARIO "valor_salario",
TO_CHAR(F.DT_ADMISSAO, 'DD/MM/YYYY') "data de admissão"
FROM T_SIP_FUNCIONARIO  F
WHERE CD_DEPTO IN (1234, 10, 30, 60, 7)
AND VL_SALARIO > 1000
ORDER BY CD_FUNC;

SELECT *
FROM T_SIP_FUNCIONARIO
WHERE DS_ESTADO_CIVIL = 'Solteiro' 
OR DS_ESTADO_CIVIL = 'Solteira';

--ou

SELECT *
FROM T_SIP_FUNCIONARIO
WHERE DS_ESTADO_CIVIL LIKE 'Solteir_' ;

SELECT *
FROM T_SIP_FUNCIONARIO
WHERE DT_ADMISSAO 
BETWEEN TO_DATE('01/01/2010', 'DD/MM/YYYY') 
AND TO_DATE('31/12/2010', 'DD/MM/YYYY');

SELECT
       CD_PROJETO,
       NM_PROJETO,
       DT_INICIO,
       DT_TERMINO,
       VL_BUDGET_PROJETO
FROM (
    SELECT CD_PROJETO,
           NM_PROJETO,
           DT_INICIO,
           DT_TERMINO,
           VL_BUDGET_PROJETO
    FROM T_SIP_PROJETO
    ORDER BY VL_BUDGET_PROJETO DESC
)
WHERE ROWNUM <= 2;

SELECT CD_PROJETO,
       NM_PROJETO,
       DT_INICIO,
       DT_TERMINO,
       VL_BUDGET_PROJETO
FROM T_SIP_PROJETO
WHERE VL_BUDGET_PROJETO > (
    SELECT AVG(VL_BUDGET_PROJETO)
    FROM T_SIP_PROJETO
    WHERE DT_TERMINO IS NULL
)
AND DT_TERMINO IS NULL;

SELECT *
FROM T_SIP_DEPTO D
WHERE (
    SELECT COUNT(CD_DEPTO)
    FROM T_SIP_FUNCIONARIO F
    WHERE F.CD_DEPTO = D.CD_DEPTO
) = 0;


SELECT *
FROM T_SIP_DEPTO d
WHERE NOT EXISTS (
    SELECT 1
    FROM T_SIP_FUNCIONARIO f
    WHERE f.CD_DEPTO = d.CD_DEPTO
);

SELECT *
FROM T_SIP_DEPTO d
WHERE d.CD_DEPTO NOT IN (
    SELECT f.CD_DEPTO
    FROM T_SIP_FUNCIONARIO f
);






